server:
  port: 10000
netty:
  port: 9070
  beatheart: 30
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.82:3306/oms?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: Root_123
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.huayun.bond.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  config: classpath:logback-spring.xml